const banks = [
    { "id": 1, "name": "Bank of the Philippine Islands(BPI)", "code": "BPI" },
    { "id": 2, "name": "Metrobank", "code": "MB" },
    { "id": 3, "name": "Philippine National Bank", "code": "PNB" },
    { "id": 4, "name": "BDO Unibank", "code": "BDO" },
    { "id": 5, "name": "UnionBank of the Philippines", "code": "UBP" },
    { "id": 6, "name": "Security Bank", "code": "SB" },
    { "id": 7, "name": "CIMB Bank", "code": "CIMB" },
    { "id": 8, "name": "ING Philippines", "code": "ING" },
    { "id": 9, "name": "Tonic Bank", "code": "TONIC" },
    { "id": 10, "name": "Maya Bank", "code": "MAYA" },
    { "id": 11, "name": "GoTyme Bank", "code": "GOTYME" },
    { "id": 12, "name": "GCash (Globe Fintech Innovations)", "code": "GCASH" },
    { "id": 13, "name": "ShopeePay", "code": "SHOPEEPAY" },
    { "id": 14, "name": "Lazada Wallet", "code": "LAZWALLET" },
    { "id": 15, "name": "GrabPay", "code": "GRABPAY" },
    { "id": 16, "name": "SeaBank Philippines", "code": "SEABANK" },
    { "id": 17, "name": "RCBC Digital", "code": "RCBC" },
    { "id": 18, "name": "Land Bank of the Philippines", "code": "LANDBANK" },
    { "id": 19, "name": "China Bank", "code": "CHINABANK" },
    { "id": 20, "name": "EastWest Bank", "code": "EW" },
    { "id": 21, "name": "Philippine Savings Bank (PSBank)", "code": "PSB" },
    { "id": 22, "name": "OMNI Pay", "code": "OMNI" },
    { "id": 23, "name": "Tonik Digital Bank", "code": "TONIK" },
    { "id": 24, "name": "DiskarTech (by RCBC)", "code": "DISKARTECH" },
    { "id": 25, "name": "Robinsons Bank", "code": "ROBINBANK" },
    { "id": 26, "name": "WealthBank", "code": "WEALTH" },
    { "id": 27, "name": "Development Bank of the Philippines", "code": "DBP" },
    { "id": 28, "name": "Payoneer", "code": "PAYONEER" },
    { "id": 39, "name": "Paypal", "code": "PAYPAL" }
  ];
  
  export default banks;